{% set name = "pyls-spyder" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5500b7b014ad4f1a3bfcd2e78a3f1160ab33622e103bdc4c775e4970478eb27

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - python-language-server

test:
  imports:
    - pyls_spyder
    - pyls_spyder.plugin

about:
  home: https://github.com/spyder-ide/pyls-spyder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Spyder extensions for the python-language-server

  description: |
    Spyder extensions for the python-language-server.
    This package provides Spyder-specific extras for the
    Language Server Protocol (LSP) on Python, such as
    document symbol searching and others.

  dev_url: https://github.com/spyder-ide/pyls-spyder

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
